[package]
name = "wget"
version = "0.1.0"
authors = ["Paul Bass <bass_p1@denison.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
